Homework1
made-ml-in-prod-2021/spin-to-win pull request #2
Opened 2021-05-09 19:19 UTC by spin-to-win

hw #1

2021-05-16 20:32 UTC, sashastds commented on README.md
> +python heart_disease_source_code/train.py
это видимо неактуально уже?
не нашёл такой директории

2021-05-16 20:32 UTC, sashastds commented on ml_project/data/output/example_predicts.csv
> +preds
некритично, и в целом тут нет айдишников, но я бы на всякий случай писал рядом индексы исходного фрейма, как хоть какой-то идентификатор

2021-05-16 20:33 UTC, sashastds commented on ml_project/src/data/make_dataset.py
> +# -*- coding: utf-8 -*-
опять же некритично, но много пустых строк в конце файлов

2021-05-16 20:37 UTC, sashastds commented on ml_project/src/features/build_features.py
> +        """ Заполнить пропуски и задать категории
прикольное решение с одной стороны, но с другой, если это категории не было в трейнсете, то и дерево сплитовать по ней не научится, так что с этой точки зрения st_slope == 3 ничем же не отличается от потенциального st_slope == 7, например, для модели с точки зрения полезной информации? но вот в последнем случае оно сломается ведь?
может имело смысл как-то все неизвестные значения маппить в одно неинформативное?

2021-05-16 20:38 UTC, sashastds commented on ml_project/src/train.py
> +from src.models.save_and_load_models import serialize_model, load_model
могу ошибаться, но вроде порядок импортов не по PEP немного

2021-05-16 20:40 UTC, sashastds commented on ml_project/src/features/build_features.py
> +class PreprocessRawData(TransformerMixin):
немного неканоничное название класса, хотя и в CamelCase, но поскольку глагол, а не например RawDataPreprocessor, чуть сбивает с толку

2021-05-16 20:41 UTC, sashastds commented on ml_project/tests/features/test_build_features.py
> +        PreprocessRawData.check_raw_data(train_data_broken)
тесты без ассертов это так и задумано?
условно если pytest не упал сам по себе == прошло?

2021-05-16 20:46 UTC, sashastds reviewed
С самооценкой согласен, у меня запустилось, обсчиталось.
Еще из мелочей - мне лично в ревью писали, что пиклы не стоит класть в гит, хотя они и мелкие.
И я не уверен, что понял, что именно считать отчётом, но EDA есть.
С гидрой выглядит так, что глубоко разбирался, круто

2021-05-17 10:48 UTC, kindofman requested changes
Название файла train.py не соответствует назначению файла. Также выполняются предсказания. Чтобы название не вводило в заблуждение, нужно поменять название ключевого скрипта.

2021-05-17 10:48 UTC, kindofman commented on README.md
> +Соответственно вернхяя оценка 30 баллов, без учета штрафов за косяки, замечения, ошибки ну и так далее - это отдаю на суд ревьюера
Для засчитывания 13-ого пункта необходима была точечная оценка.

2021-05-17 10:48 UTC, kindofman commented on ml_project/notebooks/01-exploratory_data_analysis.ipynb
> +    "pd.options.mode.chained_assignment = None     # hide any pandas warnings"
Не рекомендую так делать. Я бы постарался написать код так, чтобы SettingWithCopyWarning не пришлось отлавливать на верхнем уровне. Тем более, что и без этой строчки ноутбук запустился без ворнингов.

https://stackoverflow.com/questions/20625582/how-to-deal-with-settingwithcopywarning-in-pandas

2021-05-17 10:48 UTC, kindofman commented on README.md
> +python heart_disease_source_code/train.py
Выглядит, как будто после переименования папки забыл поправить heart_disease_source_code -> src.

2021-05-17 10:48 UTC, kindofman commented on ml_project/setup.py
> +        "Faker==8.1.4",
Не хватает библиотек для запуска ноутбука. Jupyter, matplotlib, seaborn.

2021-05-18 14:03 UTC, spin-to-win commented on ml_project/setup.py
> +        "Faker==8.1.4",
Так и задумано, чтобы не раздувать setup. 

Переделал следующим образом: переконвертировал в html и удалил ipynb, чтобы не смущать никого

2021-05-18 14:04 UTC, spin-to-win commented on README.md
> +python heart_disease_source_code/train.py
хм странно... не знаю... сейчас вроде исправил

2021-05-18 14:05 UTC, spin-to-win commented on ml_project/notebooks/01-exploratory_data_analysis.ipynb
> +    "pd.options.mode.chained_assignment = None     # hide any pandas warnings"
Done

2021-05-18 14:05 UTC, spin-to-win commented on README.md
> +Соответственно вернхяя оценка 30 баллов, без учета штрафов за косяки, замечения, ошибки ну и так далее - это отдаю на суд ревьюера
Done

Добавил точечную оценку в README.md

2021-05-18 14:06 UTC, spin-to-win commented on README.md
> +Соответственно вернхяя оценка 30 баллов, без учета штрафов за косяки, замечения, ошибки ну и так далее - это отдаю на суд ревьюера
"""Название файла train.py не соответствует назначению файла. Также выполняются предсказания. Чтобы название не вводило в заблуждение, нужно поменять название ключевого скрипта."""

Done

Сделал отдельно функцию трейн, отдельно предикт

2021-05-18 14:07 UTC, spin-to-win commented on README.md
> +python heart_disease_source_code/train.py
Да, заменил heart_disease_source_code -> src

2021-05-18 14:08 UTC, spin-to-win commented on ml_project/data/output/example_predicts.csv
> +preds
Ack

2021-05-18 14:08 UTC, spin-to-win commented on ml_project/src/data/make_dataset.py
> +# -*- coding: utf-8 -*-
Ack

2021-05-18 14:24 UTC, spin-to-win commented on ml_project/src/features/build_features.py
> +        """ Заполнить пропуски и задать категории
Ack

""" но вот в последнем случае оно сломается ведь? """ 
Да так и задумано, чтобы st_slope == 3 отработал,  а == 7 упал. Потому что 3 еще можно было бы ожидать, просто примеров в трейне не было. А вот если где-то появится неожиданная категория, например, st_slope == 7 то на этом месте по итогу будет стоять np.NaN и обучение упадет. 

"""может имело смысл как-то все неизвестные значения маппить в одно неинформативное?"""
Я правильно понимаю ты имеешь ввиду заменять неизвестные значения (типа st_slope == 7) на "unknown_category" и рейзить ошибку если найдены такие категории?

2021-05-18 14:25 UTC, spin-to-win commented on ml_project/src/features/build_features.py
> +class PreprocessRawData(TransformerMixin):
Done
Переименовал на RawDataPreprocessor

2021-05-18 14:25 UTC, spin-to-win commented on ml_project/tests/features/test_build_features.py
> +        PreprocessRawData.check_raw_data(train_data_broken)
Да, просто смоук-тест (запустили и если не пошел дым, значит все хорошо)

2021-05-23 10:47 UTC, kindofman approved these changes
Отличная работа!

31 балл.

2021-05-25 10:32 UTC, merged