Homework2
made-ml-in-prod-2021/spin-to-win pull request #3
Opened 2021-05-19 14:25 UTC by spin-to-win

2021-05-23 13:22 UTC, Mikhail-M requested changes
Добейтесь, чтобы кода первой дз не было в этом реквесте

2021-05-23 19:07 UTC, spin-to-win commented
> Добейтесь, чтобы кода первой дз не было в этом реквесте

Done

git rm -r --cached ./ml_project

2021-06-14 20:03 UTC, Mikhail-M commented
Требует доделки перед проверкой

2021-06-15 00:17 UTC, spin-to-win commented
"Требует доделки перед проверкой"
Михаил, что вы имеете в виду ? Я в гитхабе новичок, может мне нажать куда-то надо, но вроде исправил ваше замечание - код первой дз удален из этой ветки

2021-06-16 13:35 UTC, Mikhail-M approved these changes
Оптимизация: 1.5
Тесты: 2

присутствует код другой ДЗ: -1

Баллы: 22-1-1-1.5 = 18.5

2021-06-19 08:54 UTC, merged